# Generated by Django 5.1.5 on 2025-02-03 10:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('bucket_type', models.CharField(choices=[('STANDARD', 'Standard Storage Bucket'), ('EXTERNAL', 'External Provider Bucket')], default='STANDARD', editable=False, max_length=20)),
                ('external_provider', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('cluster', models.CharField(editable=False, max_length=255)),
                ('mount_enabled', models.BooleanField(default=False)),
                ('observe_enabled', models.BooleanField(default=False)),
                ('delete_permission_groups', models.ManyToManyField(blank=True, related_name='delete_buckets', to='auth.group')),
                ('mount_permission_groups', models.ManyToManyField(blank=True, related_name='mount_buckets', to='auth.group')),
                ('observe_permission_groups', models.ManyToManyField(blank=True, related_name='observe_buckets', to='auth.group')),
                ('read_permission_groups', models.ManyToManyField(blank=True, related_name='read_buckets', to='auth.group')),
                ('write_permission_groups', models.ManyToManyField(blank=True, related_name='write_buckets', to='auth.group')),
            ],
            options={
                'db_table': 'storage_bucket',
                'ordering': ['name', 'created_at'],
            },
        ),
    ]
